spring:
  application:
    name: server
  datasource:
    name: datasource
    url: jdbc:mysql://api.thuni-h.com:30526/suty?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: yV2jJxvNs8BD
    druid:
      maxActive: 20
      initialSize: 10
      maxWait: 60000
      minIdle: 1

grpc:
  server:
    port: 6565
    address: 0.0.0.0
  client:
    GLOBAL:
      address: static://localhost:6565
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

storage:
  url: http://demo.homeword.cn/files
oa:
  host: http://192.168.3.145:7002
  file:
    url: http://192.168.3.145:7002/defaultroot/UploadServlet
  link: http://192.168.3.145:7002


es:
  clustername:
    cluster_elasticsearch
  ip:
    192.168.3.35
  port:
    30300
role:
  name: 会务管理员